#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnevnik.Blocks.Views.team_banner
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/team_banner/team_banner.cshtml")]
    public partial class team_banner : System.Web.Mvc.WebViewPage<dynamic>
    {
        public team_banner()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div class=\"team_banner\">\r\n    <img src=\"http://content.adfox.ru/130918/adfox/2" +
"48366/802977.jpg\">\r\n</div>");


        }
    }
}
#pragma warning restore 1591
