#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnevnik.Blocks.Views.widgets.stats
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/widgets/stats/stats.cshtml")]
    public partial class stats : System.Web.Mvc.WebViewPage<dynamic>
    {
        public stats()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div class=\"widget widget_stats\">\r\n    <br />\r\n    <h3>Статистика</h3>\r\n    <br" +
" />\r\n</div>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
