#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnevnik.Blocks.Views.menu
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/menu/menu.cshtml")]
    public partial class menu : System.Web.Mvc.WebViewPage<dynamic>
    {
        public menu()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div class=\"menu\">\r\n    <ul class=\"menu__layout\">\r\n        <li class=\"menu__layou" +
"t-item\">\r\n            <a href=\"#\" class=\"menu__item__link menu__item__link_activ" +
"e\">Мой дневник</a>\r\n            <ul class=\"menu__item__submenu__layout menu__ite" +
"m__submenu__layout_active\">\r\n                <li class=\"menu__item__submenu__lay" +
"out-item\">\r\n                    <a href=\"#\" class=\"menu__item__submenu__item\">\r\n" +
"                        Профиль\r\n                    </a>\r\n                </li>" +
"\r\n                <li class=\"menu__item__submenu__layout-item\">\r\n               " +
"     <a href=\"#\" class=\"menu__item__submenu__item\">\r\n                        Соо" +
"бщения\r\n                    </a>\r\n                </li>\r\n                <li cla" +
"ss=\"menu__item__submenu__layout-item\">\r\n                    <a href=\"#\" class=\"m" +
"enu__item__submenu__item\">\r\n                        Почта\r\n                    <" +
"/a>\r\n                </li>\r\n            </ul>\r\n        </li>\r\n        <li class=" +
"\"menu__layout-item\">\r\n            <a href=\"#\" class=\"menu__item__link\">Общение</" +
"a>\r\n            <ul class=\"menu__item__submenu__layout\">\r\n                <li cl" +
"ass=\"menu__item__submenu__layout-item\">\r\n                    <a href=\"#\" class=\"" +
"menu__item__submenu__item\">\r\n                        Люди\r\n                    <" +
"/a>\r\n                </li>\r\n                <li class=\"menu__item__submenu__layo" +
"ut-item\">\r\n                    <a href=\"#\" class=\"menu__item__submenu__item\">\r\n " +
"                       Группы\r\n                    </a>\r\n                </li>\r\n" +
"                <li class=\"menu__item__submenu__layout-item\">\r\n                 " +
"   <a href=\"#\" class=\"menu__item__submenu__item\">\r\n                        Событ" +
"ия\r\n                    </a>\r\n                </li>\r\n            </ul>\r\n        " +
"</li>\r\n        <li class=\"menu__layout-item\">\r\n            <a href=\"#\" class=\"me" +
"nu__item__link\">Школа</a>\r\n            <ul class=\"menu__item__submenu__layout\">\r" +
"\n                <li class=\"menu__item__submenu__layout-item\">\r\n                " +
"    <a href=\"#\" class=\"menu__item__submenu__item\">\r\n                        Расп" +
"исания\r\n                    </a>\r\n                </li>\r\n                <li cla" +
"ss=\"menu__item__submenu__layout-item\">\r\n                    <a href=\"#\" class=\"m" +
"enu__item__submenu__item\">\r\n                        Журналы\r\n                   " +
" </a>\r\n                </li>\r\n                <li class=\"menu__item__submenu__la" +
"yout-item\">\r\n                    <a href=\"#\" class=\"menu__item__submenu__item\">\r" +
"\n                        Отчёты\r\n                    </a>\r\n                </li>" +
"\r\n            </ul>\r\n        </li>\r\n    </ul>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
