#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnevnik.Blocks.Views.menu
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/menu/menu.cshtml")]
    public partial class menu : System.Web.Mvc.WebViewPage<dynamic>
    {
        public menu()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"<div class=""menu"">
    <ul class=""menu__layout"">
        <li class=""menu__layout-item"">
            <a href=""#"" class=""menu__item__link menu__item__link_active"">Мой дневник</a>
            <ul class=""menu__item__submenu__layout menu__item__submenu__layout_active"">
                <li class=""menu__item__submenu__layout-item"">
                    <a href=""#"" class=""menu__item__submenu__item"">
                        ");


            
            #line 8 "..\..\Views\menu\menu.cshtml"
                   Write(Model);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </a>\r\n                </li>\r\n                <li class=\"men" +
"u__item__submenu__layout-item\">\r\n                    <a href=\"#\" class=\"menu__it" +
"em__submenu__item\">\r\n                    </a>\r\n                </li>\r\n          " +
"      <li class=\"menu__item__submenu__layout-item\">\r\n                    <a href" +
"=\"#\" class=\"menu__item__submenu__item\">\r\n                        Почта\r\n        " +
"            </a>\r\n                </li>\r\n            </ul>\r\n        </li>\r\n     " +
"   <li class=\"menu__layout-item\">\r\n            <a href=\"#\" class=\"menu__item__li" +
"nk\">Общение</a>\r\n            <ul class=\"menu__item__submenu__layout\">\r\n         " +
"       <li class=\"menu__item__submenu__layout-item\">\r\n                    <a hre" +
"f=\"#\" class=\"menu__item__submenu__item\">\r\n                        Люди\r\n        " +
"            </a>\r\n                </li>\r\n                <li class=\"menu__item__" +
"submenu__layout-item\">\r\n                    <a href=\"#\" class=\"menu__item__subme" +
"nu__item\">\r\n                        Группы\r\n                    </a>\r\n          " +
"      </li>\r\n                <li class=\"menu__item__submenu__layout-item\">\r\n    " +
"                <a href=\"#\" class=\"menu__item__submenu__item\">\r\n                " +
"        События\r\n                    </a>\r\n                </li>\r\n            </" +
"ul>\r\n        </li>\r\n        <li class=\"menu__layout-item\">\r\n            <a href=" +
"\"#\" class=\"menu__item__link\">Школа</a>\r\n            <ul class=\"menu__item__subme" +
"nu__layout\">\r\n                <li class=\"menu__item__submenu__layout-item\">\r\n   " +
"                 <a href=\"#\" class=\"menu__item__submenu__item\">\r\n               " +
"         Расписания\r\n                    </a>\r\n                </li>\r\n          " +
"      <li class=\"menu__item__submenu__layout-item\">\r\n                    <a href" +
"=\"#\" class=\"menu__item__submenu__item\">\r\n                        Журналы\r\n      " +
"              </a>\r\n                </li>\r\n                <li class=\"menu__item" +
"__submenu__layout-item\">\r\n                    <a href=\"#\" class=\"menu__item__sub" +
"menu__item\">\r\n                        Отчёты\r\n                    </a>\r\n        " +
"        </li>\r\n            </ul>\r\n        </li>\r\n    </ul>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
