#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnevnik.Blocks.Views.containers.blue
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\containers\blue\blue.cshtml"
    using Dnevnik.Blocks.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/containers/blue/blue.cshtml")]
    public partial class blue : System.Web.Mvc.WebViewPage<string>
    {
        public blue()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n<div class=\"container\">\r\n    <h3>");


            
            #line 5 "..\..\Views\containers\blue\blue.cshtml"
   Write(Model);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n    ");


            
            #line 6 "..\..\Views\containers\blue\blue.cshtml"
Write(Html.Inners());

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
