#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnevnik.Blocks.Views.social.links
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/social/links/links.cshtml")]
    public partial class links : System.Web.Mvc.WebViewPage<dynamic>
    {
        public links()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"
<div class=""links"">
    <a href=""http://twitter.com/dnevnik_ru"" title=""Дневник в Твиттере""><img src=""http://static.staging.dnevnik.ru/images/icons/twitter.png"" alt=""Twitter""></a>
    <a href=""http://www.facebook.com/dnevnik.ru"" title=""Дневник в Facebook""><img src=""http://static.staging.dnevnik.ru/images/icons/facebook.png"" alt=""Facebook""></a>
    <a href=""http://vkontakte.ru/club19853844"" title=""Дневник ВКонтакте""><img src=""http://static.staging.dnevnik.ru/images/icons/vkontakte.png"" alt=""ВКонтакте""></a>
    <a href=""http://www.odnoklassniki.ru/dnevnik.ru"" title=""Дневник в Одноклассниках""><img src=""http://static.staging.dnevnik.ru/images/icons/odnoklassniki.png"" alt=""Одноклассники""></a>
    <a href=""http://www.youtube.com/user/DnevnikVideoRussia"" title=""Дневник в YouTube""><img src=""http://static.staging.dnevnik.ru/images/icons/youtube.png"" alt=""Youtube""></a>
    <a href=""http://dnevnikru.livejournal.com"" title=""Дневник в Живом Журнале""><img src=""http://static.staging.dnevnik.ru/images/icons/livejournal.png"" alt=""LiveJournal""></a>
</div>");


        }
    }
}
#pragma warning restore 1591
