#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnevnik.Blocks.Views.profile
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/profile/profile.cshtml")]
    public partial class profile : System.Web.Mvc.WebViewPage<dynamic>
    {
        public profile()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div class=\"profile\">\r\n    <div class=\"profile__column\">\r\n        <div class=\"pro" +
"file__name\">\r\n            <a href=\"#\" title=\"Мой профиль\" class=\"profile__name__" +
"value\">\r\n                Виталий Лебедев\r\n            </a>\r\n        </div>\r\n    " +
"    <div class=\"profile__counters\">\r\n            <ul class=\"profile__counters__l" +
"ayout\">\r\n                <li class=\"profile__counters__layout-item\">\r\n          " +
"          <div>\r\n                        <a title=\"Перейти в дневник.деньги\" hre" +
"f=\"#\">\r\n                            <div class=\"profile__counters__item profile_" +
"_counters__item_img profile__counters__item_img_yandex_dengi\"></div>\r\n          " +
"              </a>\r\n                    </div>\r\n                </li>\r\n         " +
"       <li class=\"profile__counters__layout-item\">\r\n                    <div>\r\n " +
"                       <a href=\"#\">\r\n                            <div class=\"pro" +
"file__counters__item profile__counters__item_img profile__counters__item_img_wal" +
"let\"></div>\r\n                            <div class=\"profile__counters__item pro" +
"file__counters__item_value\">100.00</div>\r\n                        </a>\r\n        " +
"            </div>\r\n                </li>\r\n                <li class=\"profile__c" +
"ounters__layout-item\">\r\n                    <a href=\"#\">\r\n                      " +
"  <div class=\"profile__counters__item profile__counters__item_img profile__count" +
"ers__item_img_invitations\"></div>\r\n                        <div class=\"profile__" +
"counters__item profile__counters__item_value\">1</div>\r\n                    </a>\r" +
"\n                </li>\r\n                <li class=\"profile__counters__layout-ite" +
"m\">\r\n                    <a href=\"#\">\r\n                        <div class=\"profi" +
"le__counters__item profile__counters__item_img profile__counters__item_img_frien" +
"ds\"></div>\r\n                        <div class=\"profile__counters__item profile_" +
"_counters__item_value\">2</div>\r\n                    </a>\r\n                </li>\r" +
"\n                <li class=\"profile__counters__layout-item\">\r\n                  " +
"  <a href=\"#\">\r\n                        <div class=\"profile__counters__item prof" +
"ile__counters__item_img profile__counters__item_img_messages\"></div>\r\n          " +
"              <div class=\"profile__counters__item profile__counters__item_value\"" +
">3</div>\r\n                    </a>\r\n                </li>\r\n            </ul>\r\n  " +
"      </div>\r\n    </div>\r\n    <div class=\"profile__avatar profile__column\">\r\n   " +
"     <a href=\"#\" class=\"profile__avatar__button\">\r\n            <img src=\"http://" +
"static.staging.dnevnik.ru/images/avatars/user/a.s.jpg\" class=\"profile__avatar__b" +
"utton-img\" />\r\n        </a>\r\n    </div>\r\n    <div class=\"profile__logout profile" +
"__column\">\r\n        <a href=\"#\" class=\"profile__logout__button\"></a>\r\n    </div>" +
"\r\n</div>");


        }
    }
}
#pragma warning restore 1591
