#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnevnik.Blocks.Views.Shared.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/Single.cshtml")]
    public partial class Single : System.Web.Mvc.WebViewPage<Dnevnik.Blocks.Models.Widget>
    {
        public Single()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Shared\EditorTemplates\Single.cshtml"
   var mainclass = ViewData["mod"] ?? "single"; 

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"widget ");


            
            #line 4 "..\..\Views\Shared\EditorTemplates\Single.cshtml"
               Write("widget_" + mainclass);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n    <h3>");


            
            #line 5 "..\..\Views\Shared\EditorTemplates\Single.cshtml"
   Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n    <p>\r\n        ");


            
            #line 7 "..\..\Views\Shared\EditorTemplates\Single.cshtml"
   Write(Html.EditorFor(w => w.Content));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
